Repository WildCodeSchool/tours-php-2009-project2-quizzy, pull requests merged in 2020-11, with the labels that each got.

#6 user3-winORfail pull request
  README.md
  db.sql
  src/Controller/QuestionController.php
  src/Model/ChoiceManager.php
  src/Model/QuestionManager.php
  src/View/Question/index.html.twig
  src/View/Question/result.html.twig
  src/View/base.html.twig
Labels: Changes done

#10 user4-pass PR
  src/Controller/QuestionController.php
Labels: Reviews requested

#12 Update master
  Dockerfile
  README.md
  composer.json
  composer.lock
  config/config.php
  db.sql
  grumphp.yml
  public/index.php
  src/Controller/AbstractController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/QuestionController.php
  src/Model/AbstractManager.php
  src/Model/ChoiceManager.php
  src/Model/Connection.php
  src/Model/ItemManager.php
  src/Model/QuestionManager.php
  src/View/Question/index.html.twig
  src/View/Question/result.html.twig
  src/View/base.html.twig
  src/routing.php
Labels: Reviewed

#13 deleted the '!== false' because we want to use phps inner workings
  .gitignore
  src/Controller/QuestionController.php
  src/View/Question/index.html.twig
Labels: Reviewed

#15 UpDate Master
  .gitignore
  src/Controller/QuestionController.php
  src/View/Question/index.html.twig
Labels: Reviewed

#14 user5-add PR
  README.md
  src/Controller/ChoicesController.php
  src/Controller/QuestionController.php
  src/Controller/SessionController.php
  src/Model/ChoiceManager.php
  src/Model/ChoiceValidator.php
  src/Model/QuestionManager.php
  src/View/Choices/add.html.twig
  src/View/Choices/added.html.twig
  src/View/Question/add.html.twig
  src/View/base.html.twig
Labels: Changes done, Reviewed

#16 user0-general PR -- deleted simple mvc basics
  README.md
  config/config.php
  simple-mvc.sql
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/QuestionController.php
  src/Model/ItemManager.php
  src/View/Choices/added.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/Question/index.html.twig
  src/View/Question/result.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#17 PR Dev -> Master
  README.md
  config/config.php
  simple-mvc.sql
  src/Controller/ChoicesController.php
  src/Controller/HomeController.php
  src/Controller/ItemController.php
  src/Controller/QuestionController.php
  src/Controller/SessionController.php
  src/Model/ChoiceManager.php
  src/Model/ChoiceValidator.php
  src/Model/ItemManager.php
  src/Model/QuestionManager.php
  src/View/Choices/add.html.twig
  src/View/Choices/added.html.twig
  src/View/Home/index.html.twig
  src/View/Item/_form.html.twig
  src/View/Item/add.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/index.html.twig
  src/View/Item/show.html.twig
  src/View/Question/add.html.twig
  src/View/Question/index.html.twig
  src/View/Question/result.html.twig
  src/View/base.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#18 user7-responsive PR
  public/assets/css/added.css
  public/assets/css/choicesAdd.css
  public/assets/css/index.css
  public/assets/css/questionAdd.css
  public/assets/css/result.css
  public/assets/css/style.css
  public/assets/fonts/3Dumb.ttf
  src/Controller/InfoController.php
  src/View/Choices/add.html.twig
  src/View/Choices/added.html.twig
  src/View/Info/about.html.twig
  src/View/Info/faq.html.twig
  src/View/Info/legal.html.twig
  src/View/Question/add.html.twig
  src/View/Question/index.html.twig
  src/View/Question/result.html.twig
  src/View/base.html.twig
Labels: Reviewed

#19 User7 responsive
  public/assets/css/index.css
  public/assets/css/style.css
  public/assets/fonts/3Dumb.ttf
  public/assets/fonts/NerkoOne-Regular.ttf
  public/assets/fonts/crackman.regular.ttf
  src/View/Choices/add.html.twig
  src/View/Choices/added.html.twig
  src/View/Question/add.html.twig
Labels: Reviewed

#20 PR dev master style
  public/assets/css/added.css
  public/assets/css/choicesAdd.css
  public/assets/css/index.css
  public/assets/css/questionAdd.css
  public/assets/css/result.css
  public/assets/css/style.css
  public/assets/fonts/NerkoOne-Regular.ttf
  public/assets/fonts/crackman.regular.ttf
  src/Controller/InfoController.php
  src/View/Choices/add.html.twig
  src/View/Choices/added.html.twig
  src/View/Info/about.html.twig
  src/View/Info/faq.html.twig
  src/View/Info/legal.html.twig
  src/View/Question/add.html.twig
  src/View/Question/index.html.twig
  src/View/Question/result.html.twig
  src/View/base.html.twig
Labels: Reviewed

#28 User0 general
  public/assets/css/about.css
  public/assets/css/index.css
  public/assets/images/Flo.png
  public/assets/images/Lu.png
  public/assets/images/Max.png
  public/assets/images/Y.png
  src/View/Info/about.html.twig
  src/View/Info/faq.html.twig
  src/View/Info/legal.html.twig
Labels: Reviewed

#31 User7 responsive
  public/assets/css/about.css
  public/assets/css/index.css
  public/assets/css/info.css
  public/assets/css/result.css
  public/assets/css/style.css
  public/assets/images/background.png
  src/View/Choices/add.html.twig
  src/View/Info/about.html.twig
  src/View/Info/faq.html.twig
  src/View/Info/legal.html.twig
  src/View/Question/add.html.twig
  src/View/Question/index.html.twig
Labels: Reviewed

#32 final Project PR
  public/assets/css/about.css
  public/assets/css/index.css
  public/assets/css/info.css
  public/assets/css/result.css
  public/assets/css/style.css
  public/assets/images/Flo.png
  public/assets/images/Lu.png
  public/assets/images/Max.png
  public/assets/images/Y.png
  public/assets/images/background.png
  src/View/Choices/add.html.twig
  src/View/Info/about.html.twig
  src/View/Info/faq.html.twig
  src/View/Info/legal.html.twig
  src/View/Question/add.html.twig
  src/View/Question/index.html.twig
Labels: Reviewed

#33 very very very absolutely final commit
  public/assets/css/index.css
  public/assets/css/style.css
Labels: Reviewed

#34 The end
  public/assets/css/index.css
  public/assets/css/style.css
Labels: Reviewed
